### PR TITLE
Kernel fixes

### PR DESCRIPTION
**Pull request by shankerd04**
- Two patches are for defconfig
-  EFI-RTC fix, working with EFI & RTC maintainers
-  Increase the number of IRQ descriptors, started discussion with the maintainer

### CODE REVIEW

**Comment by nvidia-bfigg** [comment]
The optimized Ubuntu kernel for Nvidia does not use defconfig it uses the configuration as defined by files under debian.nvidia-5.19. Do you want me to apply your defconfig changes to the Ubuntu configuration files?

**Comment by shankerd04** [comment]
> The optimized Ubuntu kernel for Nvidia does not use defconfig it uses the configuration as defined by files under debian.nvidia-5.19. Do you want me to apply your defconfig changes to the Ubuntu configuration files?

Yes, both options are must for CG4

**Comment by nvidia-bfigg** [comment]
Are the other two patches going upstream and if so do you have a target for which merge cycle you will be targeting?

**Comment by shankerd04** [comment]
> Are the other two patches going upstream and if so do you have a target for which merge cycle you will be targeting?

Started discussing with maintainers recently.
1) https://lkml.org/lkml/2023/1/3/168 --> likely to be in v6.2 and might be back-ported to stable branches 
2) https://lkml.org/lkml/2023/1/5/625 --> Most probably this patch will be replaced by a scalable solution that fixes other ARCHs

**Comment by nvidia-bfigg** [comment]
Thank you for quickly answering my questions. I'll get these to Canonical and get them incorporated as soon as possible.

**Pull request closed without merging**
